CREATE PROCEDURE INSERT_TKA_T_AUDIT_TRAIL_OCRD_DETAILED(
out "OUTPUT" TABLE(RESULT INT)
)
AS
 BEGIN 
 	TRUNCATE TABLE TKA_T_AUDIT_TRAIL_OCRD_DETAILED;
 	
 	
 	INSERT INTO TKA_T_AUDIT_TRAIL_OCRD_DETAILED
 	("U_AA","CardCode", "UserSign","Creator","UserSign2", "Modifier","CreateDate","UpdateDate", "LogInstanc",
 	"previous_Διακριτικός Τίτλος","current_Διακριτικός Τίτλος","Διακριτικός Τίτλος",
	"previous_Λογιστική Ομάδα","current_Λογιστική Ομάδα","Λογιστική Ομάδα",
	"previous_Α.Φ.Μ","current_Α.Φ.Μ","Α.Φ.Μ",
	"previous_Επωνυμία", "current_Επωνυμία","Επωνυμία",
	"previous_Ενδοομιλ. Συναλλαγές","current_Ενδοομιλ. Συναλλαγές","Ενδοομιλ. Συναλλαγές",
	"previous_ΈλεγχοςΠιστωτ. Πολιτικής", "current_ΈλεγχοςΠιστωτ. Πολιτικής","ΈλεγχοςΠιστωτ. Πολιτικής",
	"previous_Αδραν.ως προς Πίστωση", "current_Αδραν.ως προς Πίστωση","Αδραν.ως προς Πίστωση",
	"previous_Αξιολόγηση Πιστοληπτική", "current_Αξιολόγηση Πιστοληπτική","Αξιολόγηση Πιστοληπτική",
	"previous_CRM Code","current_CRM Code","CRM Code",
	"previous_Εντός Ρύθμισης", "current_Εντός Ρύθμισης","Εντός Ρύθμισης",
	"previous_Κατηγορία Προμηθευτή", "current_Κατηγορία Προμηθευτή","Κατηγορία Προμηθευτή",
	"previous_Τύπος Προμηθευτή", "current_Τύπος Προμηθευτή","Τύπος Προμηθευτή",
	"previous_Αδραν. Πιστωτή προς πλη", "current_Αδραν. Πιστωτή προς πλη","Αδραν. Πιστωτή προς πλη",
	"previous_Κύκλος Πληρωμών", "current_Κύκλος Πληρωμών","Κύκλος Πληρωμών",
	"previous_Περιοδικός Έλεγχος", "current_Περιοδικός Έλεγχος","Περιοδικός Έλεγχος",
	"previous_Risk Assessment", "current_Risk Assessment","Risk Assessment",
	"previous_Compliance Risk Assessm", "current_Compliance Risk Assessm","Compliance Risk Assessm",
	"previous_Legal Assessment", "current_Legal Assessment","Legal Assessment",
	"previous_IT Assessments", "current_IT Assessments","IT Assessments",
	"previous_GDPR Renewal","current_GDPR Renewal","GDPR Renewal",
	"previous_Quality Assessment", "current_Quality Assessment","Quality Assessment",
	"previous_1η Κατηγορία Πελάτη","current_1η Κατηγορία Πελάτη","1η Κατηγορία Πελάτη",
	"previous_2η Κατηγορία Πελάτη", "current_2η Κατηγορία Πελάτη","2η Κατηγορία Πελάτη",
	"previous_3η Κατηγορία Πελάτη", "current_3η Κατηγορία Πελάτη","3η Κατηγορία Πελάτη",
	"previous_Ανήκει σε Όμιλο", "current_Ανήκει σε Όμιλο","Ανήκει σε Όμιλο",
	"previous_Όμιλος", "current_Όμιλος","Όμιλος",
	"previous_Δημοσιοποίηση Ε.Ο.Φ.", "current_Δημοσιοποίηση Ε.Ο.Φ.","Δημοσιοποίηση Ε.Ο.Φ.",
	"previous_ΑΦΜ(Γενικά)", "current_ΑΦΜ(Γενικά)","ΑΦΜ(Γενικά)",
	"previous_Κωδικός Επαγγέλματος", "current_Κωδικός Επαγγέλματος","Κωδικός Επαγγέλματος",
	"previous_Επάγγελμα", "current_Επάγγελμα","Επάγγελμα",
	"previous_Καθεστώς Φ.Π.Α", "current_Καθεστώς Φ.Π.Α","Καθεστώς Φ.Π.Α",
	"previous_Α.Φ.Μ (Διευθύνσεις)", "current_Α.Φ.Μ (Διευθύνσεις)","Α.Φ.Μ (Διευθύνσεις)",
	"previous_Όροι Πληρωμής", "current_Όροι Πληρωμής","Όροι Πληρωμής",
	"previous_Τιμοκατάλογος", "current_Τιμοκατάλογος","Τιμοκατάλογος",
	"previous_Πιστωτικό Όριο", "current_Πιστωτικό Όριο","Πιστωτικό Όριο",
	"previous_Ομάδες Ισχύουσας Έκπτωσης", "current_Ομάδες Ισχύουσας Έκπτωσης","Ομάδες Ισχύουσας Έκπτωσης",
	"previous_Όνομα Τράπεζας", "current_Όνομα Τράπεζας","Όνομα Τράπεζας",
	"previous_Τραπεζικός Κωδικός", "current_Τραπεζικός Κωδικός","Τραπεζικός Κωδικός",
	"previous_Λ/σμος Τράπεζας","current_Λ/σμος Τράπεζας","Λ/σμος Τράπεζας",
	"previous_Κωδικός BIC/SWIFT", "current_Κωδικός BIC/SWIFT","Κωδικός BIC/SWIFT",
	"previous_IBAN","current_IBAN","IBAN",
	"previous_Προτεινόμενο IBAN", "current_Προτεινόμενο IBAN","Προτεινόμενο IBAN",
	"previous_Τράπεζα", "current_Τράπεζα","Τράπεζα",
	"previous_Λ/σμος Γ/Λ", "current_Λ/σμος Γ/Λ","Λ/σμος Γ/Λ",
	"previous_Υποκατάστημα", "current_Υποκατάστημα","Υποκατάστημα",
	"previous_IBAN(Εκτέλεση Προγράμματος)", "current_IBAN(Εκτέλεση Προγράμματος)","IBAN(Εκτέλεση Προγράμματος)",
	"previous_Κωδικός BIC/SWIFT(Εκτέλεση Προγράμματος)", "current_Κωδικός BIC/SWIFT(Εκτέλεση Προγράμματος)","Κωδικός BIC/SWIFT(Εκτέλεση Προγράμματος)",
 	 "Changed_Fields")
 	SELECT ROW_NUMBER()OVER (ORDER BY "CardCode" ASC, "LogInstanc" DESC),"CardCode", "UserSign","Creator","UserSign2", 
 	IFNULL("Modifier",'dtw') AS "Modifier",
 	CAST("CreateDate" AS DATE),CAST("UpdateDate" AS DATE), "LogInstanc",
 	"previous_Διακριτικός Τίτλος","current_Διακριτικός Τίτλος","Διακριτικός Τίτλος",
	"previous_Λογιστική Ομάδα","current_Λογιστική Ομάδα","Λογιστική Ομάδα",
	"previous_Α.Φ.Μ","current_Α.Φ.Μ","Α.Φ.Μ",
	"previous_Επωνυμία", "current_Επωνυμία","Επωνυμία",
	"previous_Ενδοομιλ. Συναλλαγές","current_Ενδοομιλ. Συναλλαγές","Ενδοομιλ. Συναλλαγές",
	"previous_ΈλεγχοςΠιστωτ. Πολιτικής", "current_ΈλεγχοςΠιστωτ. Πολιτικής","ΈλεγχοςΠιστωτ. Πολιτικής",
	"previous_Αδραν.ως προς Πίστωση", "current_Αδραν.ως προς Πίστωση","Αδραν.ως προς Πίστωση",
	"previous_Αξιολόγηση Πιστοληπτική", "current_Αξιολόγηση Πιστοληπτική","Αξιολόγηση Πιστοληπτική",
	"previous_CRM Code","current_CRM Code","CRM Code",
	"previous_Εντός Ρύθμισης", "current_Εντός Ρύθμισης","Εντός Ρύθμισης",
	"previous_Κατηγορία Προμηθευτή", "current_Κατηγορία Προμηθευτή","Κατηγορία Προμηθευτή",
	"previous_Τύπος Προμηθευτή", "current_Τύπος Προμηθευτή","Τύπος Προμηθευτή",
	"previous_Αδραν. Πιστωτή προς πλη", "current_Αδραν. Πιστωτή προς πλη","Αδραν. Πιστωτή προς πλη",
	"previous_Κύκλος Πληρωμών", "current_Κύκλος Πληρωμών","Κύκλος Πληρωμών",
	"previous_Περιοδικός Έλεγχος", "current_Περιοδικός Έλεγχος","Περιοδικός Έλεγχος",
	"previous_Risk Assessment", "current_Risk Assessment","Risk Assessment",
	"previous_Compliance Risk Assessm", "current_Compliance Risk Assessm","Compliance Risk Assessm",
	"previous_Legal Assessment", "current_Legal Assessment","Legal Assessment",
	"previous_IT Assessments", "current_IT Assessments","IT Assessments",
	"previous_GDPR Renewal","current_GDPR Renewal","GDPR Renewal",
	"previous_Quality Assessment", "current_Quality Assessment","Quality Assessment",
	"previous_1η Κατηγορία Πελάτη","current_1η Κατηγορία Πελάτη","1η Κατηγορία Πελάτη",
	"previous_2η Κατηγορία Πελάτη", "current_2η Κατηγορία Πελάτη","2η Κατηγορία Πελάτη",
	"previous_3η Κατηγορία Πελάτη", "current_3η Κατηγορία Πελάτη","3η Κατηγορία Πελάτη",
	"previous_Ανήκει σε Όμιλο", "current_Ανήκει σε Όμιλο","Ανήκει σε Όμιλο",
	"previous_Όμιλος", "current_Όμιλος","Όμιλος",
	"previous_Δημοσιοποίηση Ε.Ο.Φ.", "current_Δημοσιοποίηση Ε.Ο.Φ.","Δημοσιοποίηση Ε.Ο.Φ.",
	"previous_ΑΦΜ(Γενικά)", "current_ΑΦΜ(Γενικά)","ΑΦΜ(Γενικά)",
	"previous_Κωδικός Επαγγέλματος", "current_Κωδικός Επαγγέλματος","Κωδικός Επαγγέλματος",
	"previous_Επάγγελμα", "current_Επάγγελμα","Επάγγελμα",
	"previous_Καθεστώς Φ.Π.Α", "current_Καθεστώς Φ.Π.Α","Καθεστώς Φ.Π.Α",
	"previous_Α.Φ.Μ (Διευθύνσεις)", "current_Α.Φ.Μ (Διευθύνσεις)","Α.Φ.Μ (Διευθύνσεις)",
	"previous_Όροι Πληρωμής", "current_Όροι Πληρωμής","Όροι Πληρωμής",
	"previous_Τιμοκατάλογος", "current_Τιμοκατάλογος","Τιμοκατάλογος",
	"previous_Πιστωτικό Όριο", "current_Πιστωτικό Όριο","Πιστωτικό Όριο",
	"previous_Ομάδες Ισχύουσας Έκπτωσης", "current_Ομάδες Ισχύουσας Έκπτωσης","Ομάδες Ισχύουσας Έκπτωσης",
	"previous_Όνομα Τράπεζας", "current_Όνομα Τράπεζας","Όνομα Τράπεζας",
	"previous_Τραπεζικός Κωδικός", "current_Τραπεζικός Κωδικός","Τραπεζικός Κωδικός",
	"previous_Λ/σμος Τράπεζας","current_Λ/σμος Τράπεζας","Λ/σμος Τράπεζας",
	"previous_Κωδικός BIC/SWIFT", "current_Κωδικός BIC/SWIFT","Κωδικός BIC/SWIFT",
	"previous_IBAN","current_IBAN","IBAN",
	"previous_Προτεινόμενο IBAN", "current_Προτεινόμενο IBAN","Προτεινόμενο IBAN",
	"previous_Τράπεζα", "current_Τράπεζα","Τράπεζα",
	"previous_Λ/σμος Γ/Λ", "current_Λ/σμος Γ/Λ","Λ/σμος Γ/Λ",
	"previous_Υποκατάστημα", "current_Υποκατάστημα","Υποκατάστημα",
	"previous_IBAN(Εκτέλεση Προγράμματος)", "current_IBAN(Εκτέλεση Προγράμματος)","IBAN(Εκτέλεση Προγράμματος)",
	"previous_Κωδικός BIC/SWIFT(Εκτέλεση Προγράμματος)", "current_Κωδικός BIC/SWIFT(Εκτέλεση Προγράμματος)","Κωδικός BIC/SWIFT(Εκτέλεση Προγράμματος)",
 	"Changed_Fields" 
 	FROM TKA_V_AUDIT_TRAIL_OCRD_MERGED_CHANGES
 	WHERE 1=1
 		AND "Changed_Fields"!='NoChanges'
 		AND "LogInstanc" IS NOT NULL;
 		
 		 	"OUTPUT"=SELECT 1 AS RESULT FROM DUMMY;		
 		
END