CREATE PROCEDURE INSERT_TKA_T_AUDIT_TRAIL_OITM_SUMMARY(
out "OUTPUT" TABLE(RESULT INT)
)
AS
 BEGIN 
 
 	TRUNCATE TABLE TKA_T_AUDIT_TRAIL_OITM_SUMMARY;
 
 	INSERT INTO TKA_T_AUDIT_TRAIL_OITM_SUMMARY
 	 ("U_AA","ItemCode", "Modifier","UpdateDate","Changed_Fields")
 	SELECT "U_AA","ItemCode","Modifier","UpdateDate","Changed_Fields" 
 	FROM TKA_T_AUDIT_TRAIL_OITM_DETAILED;
 	
 	 	"OUTPUT"=SELECT 1 AS RESULT FROM DUMMY;		
 	
END