CREATE PROCEDURE INSERT_TKA_T_AUDIT_TRAIL_OCRD_SUMMARY(
out "OUTPUT" TABLE(RESULT INT)
)
AS
 BEGIN 
 	TRUNCATE TABLE TKA_T_AUDIT_TRAIL_OCRD_SUMMARY;
 	
 	INSERT INTO TKA_T_AUDIT_TRAIL_OCRD_SUMMARY
 	 ("U_AA","CardCode", "Modifier","UpdateDate","Changed_Fields")
 	SELECT "U_AA","CardCode","Modifier","UpdateDate","Changed_Fields" 
 	FROM TKA_T_AUDIT_TRAIL_OCRD_DETAILED;
  	"OUTPUT"=SELECT 1 AS RESULT FROM DUMMY;		
 
END