CREATE PROCEDURE INSERT_TKA_T_AUDIT_TRAIL_OHEM_SUMMARY(
out "OUTPUT" TABLE(RESULT INT)
)
AS
 BEGIN 
 	TRUNCATE TABLE TKA_T_AUDIT_TRAIL_OHEM_SUMMARY;
 	INSERT INTO TKA_T_AUDIT_TRAIL_OHEM_SUMMARY
 	 ("U_AA","empID", "Modifier","UpdateDate","Changed_Fields")
 	SELECT "U_AA","empID","Modifier","UpdateDate","Changed_Fields" 
 	FROM TKA_T_AUDIT_TRAIL_OHEM_DETAILED;
 	 	"OUTPUT"=SELECT 1 AS RESULT FROM DUMMY;		
 	
END