CREATE PROCEDURE INSERT_TKA_T_AUDIT_TRAIL_OACT_SUMMARY(
out "OUTPUT" TABLE(RESULT INT)
)
AS
 BEGIN 
 
 	TRUNCATE TABLE TKA_T_AUDIT_TRAIL_OACT_SUMMARY;
 
 	INSERT INTO TKA_T_AUDIT_TRAIL_OACT_SUMMARY
 	 ("U_AA","AcctCode", "Modifier","UpdateDate","Changed_Fields")
 	SELECT "U_AA","AcctCode","Modifier","UpdateDate","Changed_Fields" 
 	FROM TKA_T_AUDIT_TRAIL_OACT_DETAILED;
 	
 	"OUTPUT"=SELECT 1 AS RESULT FROM DUMMY;		
END