CREATE VIEW "PHAR_PROD"."TKA_V_AUDIT_TRAIL_OCRD_ALL_DATA" ( "CardCode", "CardName", "GroupCode", "LicTradNum", "U_TKA_Eponumia", "UserSign", "Creator", "UserSign2", "Modifier", "CreateDate", "UpdateDate", "U_TKA_Endoomilikes", "U_TKA_PistotikiPolitiki", "U_TKA_AdranopoiisiPistosis", "U_TKA_SecurityCode", "U_TKA_CRMCode", "U_TKA_EntosRithmisis", "U_TKA_Category", "U_TKA_Category_DESCR", "U_TKA_Type", "U_TKA_Type_DESCR", "U_TKA_PaymentBlock", "U_TKA_PaymentCycle", "U_TKA_PeriodMonitoring", "U_TKA_RiskAssesment", "U_TKA_ComplianceRiskAssess", "U_TKA_LegalAssess", "U_TKA_ITAssessments", "U_TKA_GDPR", "U_TKA_QualityAssessment", "U_TKA_CustCategory", "U_TKA_CustCategory_DESCR", "U_TKA_CustSuBCategory", "U_TKA_SubCSubCateg", "U_TKA_Omilos", "U_TKA_OmilosList", "U_TKA_OmilosList_DESCR", "U_TKA_EOF_Dimosiop", "AddID", "U_TKA_BusinessCode", "Notes", "County", "LicTradNum2", "GroupNum", "GroupNum_DESCR", "ListNum", "ListNum_DESCR", "CreditLine", "DiscRel", "BankCode_DESCR", "BankCode", "DflAccount", "DflSwift", "DflIBAN", "IBAN", "HouseBank", "HouseBank_DESCR", "HousBnkAct", "HousBnkBrn", "HsBnkIBAN", "HsBnkSwift", "LogInstanc" ) AS SELECT
	 h."CardCode",
	 h."CardName",
	 h."GroupCode",
	 h."LicTradNum",
	 h."U_TKA_Eponumia",
	 h."UserSign",
	 U1."U_NAME" AS "Creator",
	h."UserSign2",
	 U2."U_NAME" AS "Modifier",
	 h."CreateDate",
	IFNULL(h."UpdateDate",
	h."CreateDate") AS "UpdateDate",
	 h."U_TKA_Endoomilikes",
	 h."U_TKA_PistotikiPolitiki",
	 h."U_TKA_AdranopoiisiPistosis",
	 h."U_TKA_SecurityCode",
	 h."U_TKA_CRMCode",
	 h."U_TKA_EntosRithmisis",
	 h."U_TKA_Category",
	 F."Descr" AS "U_TKA_Category_DESCR",
	 h."U_TKA_Type",
	 F1."Descr" AS "U_TKA_Type_DESCR",
	 h."U_TKA_PaymentBlock",
	 h."U_TKA_PaymentCycle",
	 h."U_TKA_PeriodMonitoring",
	 h."U_TKA_RiskAssesment",
	 h."U_TKA_ComplianceRiskAssess",
	 h."U_TKA_LegalAssess",
	 h."U_TKA_ITAssessments",
	 h."U_TKA_GDPR",
	 h."U_TKA_QualityAssessment",
	 h."U_TKA_CustCategory",
	 C."Name" AS "U_TKA_CustCategory_DESCR",
	 h."U_TKA_CustSuBCategory",
	 h."U_TKA_SubCSubCateg",
	 h."U_TKA_Omilos",
	 h."U_TKA_OmilosList",
	 O."Name" AS "U_TKA_OmilosList_DESCR",
	 h."U_TKA_EOF_Dimosiop",
	 h."AddID",
	 h."U_TKA_BusinessCode",
	 h."Notes",
	 D1."County",
	 D1."LicTradNum" AS "LicTradNum2",
	 h."GroupNum",
	 G."PymntGroup" AS "GroupNum_DESCR",
	 h."ListNum",
	 N."ListName" AS "ListNum_DESCR",
	 h."CreditLine",
	 h."DiscRel",
	 DD."BankName" AS "BankCode_DESCR",
	 h."BankCode",
	 h."DflAccount",
	 h."DflSwift",
	 h."DflIBAN",
	 h."IBAN",
	 h."HouseBank",
	 D."BankName" AS "HouseBank_DESCR",
	 h."HousBnkAct",
	 h."HousBnkBrn",
	 h."HsBnkIBAN",
	 h."HsBnkSwift",
	 h."LogInstanc" AS "LogInstanc" 
FROM ( SELECT
	 "CardCode",
	"CardName",
	"GroupCode",
	"LicTradNum",
	"U_TKA_Eponumia",
	 "UserSign",
	"UserSign2",
	"CreateDate",
	"UpdateDate",
	 "U_TKA_Endoomilikes",
	 "U_TKA_PistotikiPolitiki",
	"U_TKA_AdranopoiisiPistosis",
	"U_TKA_SecurityCode",
	"U_TKA_CRMCode",
	"U_TKA_EntosRithmisis",
	 "U_TKA_Category",
	"U_TKA_Type",
	"U_TKA_PaymentBlock",
	"U_TKA_PaymentCycle",
	"U_TKA_PeriodMonitoring",
	"U_TKA_RiskAssesment",
	 "U_TKA_ComplianceRiskAssess",
	"U_TKA_LegalAssess",
	"U_TKA_ITAssessments",
	 "U_TKA_GDPR",
	"U_TKA_QualityAssessment",
	 "U_TKA_CustCategory",
	"U_TKA_CustSuBCategory",
	"U_TKA_SubCSubCateg",
	 "U_TKA_Omilos",
	"U_TKA_OmilosList",
	"U_TKA_EOF_Dimosiop",
	 "AddID",
	"U_TKA_BusinessCode",
	"Notes",
	"GroupNum",
	"ListNum",
	"CreditLine",
	"DiscRel",
	"BankCode",
	"DflAccount",
	"DflSwift",
	"DflIBAN",
	"IBAN",
	 "HouseBank",
	"HousBnkAct",
	"HousBnkBrn",
	"HsBnkIBAN",
	"HsBnkSwift",
	"DflBankKey",
	 "LogInstanc" 
	FROM ACRD A 
	UNION ALL SELECT
	 "CardCode",
	"CardName",
	"GroupCode",
	"LicTradNum",
	"U_TKA_Eponumia",
	 "UserSign",
	"UserSign2",
	"CreateDate",
	"UpdateDate",
	 "U_TKA_Endoomilikes",
	 "U_TKA_PistotikiPolitiki",
	"U_TKA_AdranopoiisiPistosis",
	"U_TKA_SecurityCode",
	"U_TKA_CRMCode",
	"U_TKA_EntosRithmisis",
	 "U_TKA_Category",
	"U_TKA_Type",
	"U_TKA_PaymentBlock",
	"U_TKA_PaymentCycle",
	"U_TKA_PeriodMonitoring",
	"U_TKA_RiskAssesment",
	 "U_TKA_ComplianceRiskAssess",
	"U_TKA_LegalAssess",
	"U_TKA_ITAssessments",
	 "U_TKA_GDPR",
	"U_TKA_QualityAssessment",
	 "U_TKA_CustCategory",
	"U_TKA_CustSuBCategory",
	"U_TKA_SubCSubCateg",
	 "U_TKA_Omilos",
	"U_TKA_OmilosList",
	"U_TKA_EOF_Dimosiop",
	 "AddID",
	"U_TKA_BusinessCode",
	"Notes",
	"GroupNum",
	"ListNum",
	"CreditLine",
	"DiscRel",
	"BankCode",
	"DflAccount",
	"DflSwift",
	"DflIBAN",
	"IBAN",
	 "HouseBank",
	"HousBnkAct",
	"HousBnkBrn",
	"HsBnkIBAN",
	"HsBnkSwift",
	"DflBankKey",
	 (SELECT
	 MAX(R."LogInstanc")+1 
		FROM ACRD R 
		WHERE R."CardCode" = OCRD."CardCode") AS "LogInstanc" 
	FROM OCRD ) h 
LEFT JOIN OUSR U1 ON h."UserSign" = U1."INTERNAL_K" 
LEFT JOIN OUSR U2 ON h."UserSign2" = U2."INTERNAL_K" 
LEFT JOIN CRD1 D1 ON h."CardCode" = D1."CardCode" 
LEFT JOIN OCTG G ON h."GroupNum" = G."GroupNum" 
LEFT JOIN OPLN N ON h."ListNum" = N."ListNum" 
LEFT JOIN UFD1 F ON h."U_TKA_Category" = F."FldValue" 
AND F."TableID"='OCRD' 
AND F."FieldID"=22 
LEFT JOIN UFD1 F1 ON h."U_TKA_Type" = F1."FldValue" 
AND F1."TableID"='OCRD' 
AND F1."FieldID"=23 
LEFT JOIN "@ΤΚΑ_CUSTCATEGORY" C ON h."U_TKA_CustCategory" = C."Code" 
LEFT JOIN "@TKA_OMILOS" O ON h."U_TKA_OmilosList" = O."Code" 
LEFT JOIN ODSC D ON h."HouseBank" = D."BankCode" 
LEFT JOIN ODSC DD ON h."BankCode" = DD."BankCode" WITH READ ONLY